version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
      - webserver
    volumes:
      - ./:/app
    networks:
      - app-network
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis:
    driver: local